/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Array: typeof import('./src/components/FormRender/array.vue')['default']
    Collapse: typeof import('./src/components/FormRender/expand/collapse.vue')['default']
    CollapseRender: typeof import('./src/components/CollapseRender/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FormRender: typeof import('./src/components/FormRender/index.vue')['default']
    HeaderRender: typeof import('./src/components/HeaderRender/index.vue')['default']
    Item: typeof import('./src/components/CollapseRender/item.vue')['default']
    Object: typeof import('./src/components/FormRender/object.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Widget: typeof import('./src/components/FormRender/widget.vue')['default']
  }
}
